<a href="https://colab.research.google.com/github/RIPS-2024-Aerospace/Aerospace-Project/blob/main/MSE_Minimization_WithBFGS_LTT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/RIPS-2024-Aerospace/Aerospace-Project.git

Cloning into 'Aerospace-Project'...
remote: Enumerating objects: 506, done.
remote: Counting objects: 100% (237/237), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 506 (delta 155), reused 93 (delta 61), pack-reused 269
Receiving objects: 100% (506/506), 31.47 MiB | 7.96 MiB/s, done.
Resolving deltas: 100% (245/245), done.


In [6]:
import numpy as np
import random
import math
import scipy as sp

np.random.seed(29)

%run "/content/Aerospace-Project/DiffusionLunarKF.ipynb"
%run "/content/Aerospace-Project/CentralizedLunarKF.ipynb"
%run "/content/Aerospace-Project/FilterComparison.ipynb"


In [24]:
msmts_arr = [3,3,3,3,3]

In [7]:
#Generates a random edge weighting for Lunar network
#Output is vector of size 8, weights correspond to edges: [(1,2), (1,3), (1,4), (1,5), (2,1), (3,1), (4,1), (5,1)]
def gen_first_guess():
  weights = []
  temp = []
  for i in range(5):
    temp.append(random.random())
  weights = [w/sum(temp) for w in [temp[i] for i in range(4)]]
  for j in range(4):
    edge_node = [random.random()]
    weights += edge_node
  return weights

In [8]:
#Converts len=8 vector to full adjacency matrix for use in filtering
def convert_to_adj(weights):
  network = []
  temp = []
  for i in range(4):
    temp.append(weights[i])
  network.append(1-sum(temp))
  network += temp
  for i in range(4, len(weights)):
    network.append(weights[i])
    network.append(1-weights[i])



  ref = np.array([[0.2,0.2,0.2,0.2,0.2], [0.5, 0.5, 0, 0,0], [0.5, 0, 0.5, 0,0], [0.5,0,0, 0.5,0],[0.5,0,0,0,0.5]]) #This just serves as reference for where there are edges
  W = []
  i = 0
  for arr in ref:
    for val in arr:
      if val != 0:
        W.append(network[i])
        i += 1
      else: W.append(0)
  adj_matrix = np.array([[W[i] for i in range(0,5)], [W[i] for i in range(5,10)], [W[i] for i in range(10,15)], [W[i] for i in range(15,20)], [W[i] for i in range(20,25)]])
  return(adj_matrix)

In [11]:
def MSE(vec):
    adj = np.array([[1,1,1,1,1],[1,1,0,0,0],[1,0,1,0,0],[1,0,0,1,0],[1,0,0,0,1]])

    C = convert_to_adj(vec)
    n = len(C)

    D = 3*adj
    D_ckf = 3*np.ones((n,n))

    np.random.seed(29)
    true_biases = np.array([[np.random.normal(0,np.sqrt(12/(c**2))) for _ in range(n)]]).T
    true_drifts = np.array([[np.random.normal(0,np.sqrt(0.1/(c**2))) for _ in range(n)]]).T
    # true_drifts = np.array([[0 for _ in range(n)]]).T

    F = np.array([[1,dt],[0,1]])
    F_full = np.kron(np.eye(n),F)

    x = c*np.vstack(tuple([np.array([true_biases[i],true_drifts[i]]) for i in range(n)]))

    # random initial estimates for each node

    x0 = [np.array([[np.random.normal(0,np.sqrt(12))],[np.random.normal(0,np.sqrt(0.1))]]) for i in range(n)]
    x0_cf = np.vstack(tuple(x0))
    # x0 = [np.array([[0],[0]]) for _ in range(n)]

    P = [100*np.copy(R(1)) for _ in range(n)]
    P_prev = np.block([[P[i] if i==j else np.zeros((2,2)) for j in range(n)] for i in range(n)])

    stations = [Station(i) for i in range(n)]

    filter_initialize(stations,D,x0,P)

    Q_10x10 = np.kron(np.eye(n),Q)

    kf = KalmanFilter(A = F_full, H = H_cf, Q = Q_10x10, R = R_cf, P = P_prev, x0 = x0_cf)

    iterations = 100

    # num_msmts = np.random.randint(0,10,(iterations,5))
    num_msmts = np.array([msmts_arr for _ in range(iterations)])

    filter_outputs = run_both_filters(iterations, num_msmts,C,F_full,stations,kf, x)

    errors_df,errors_cf,P_hist_cf,P_hist_df,truth,measurements,predictions_cf,predictions_df = filter_outputs
    squared_error_iteration = lambda i: sum([x**2 for x in errors_df[i,:,0,0]])
    return sum([x**2 for x in [squared_error_iteration(i) for i in range(iterations)]])/(n*iterations)

In [30]:
def test_MSE():
    x0 = [0.2, 0.2, 0.2, 0.2, 0.01, 0.01, 0.01, 0.01]

    change_sat_measurements([5,0,0,5,5])
    print("Satellite measurements:", msmts_arr)

    #My guess for good weights
    x1 = [0,0,0.3,0.3,0.5,0.5,0.5,0.5]
    print("MSE for my guess 1: ", MSE(x1))
    x2 = [0,0,0.3,0.3,0.9,0.9,0.4,0.4]
    print("MSE for my guess 2:", MSE(x2))
    x3 = [0.1,0.1,0.3,0.3,0.9,0.9,0.3,0.3]
    print("MSE for my guess 2:", MSE(x3))
    print("MSE for equal weights:", MSE(x0))
#test_MSE()

Satellite measurements: [5, 0, 0, 5, 5]
MSE for my guess 1:  167.50068247838078
MSE for my guess 2: 341.36003408315554
MSE for my guess 2: 319.33563430040857
MSE for equal weights: 607869.1165414653


In [31]:
#Run BFGS for LTT
def mse_bfgs():

  #Linear Constraints:
  A = np.array([[1,0,0,0,0,0,0,0],
              [0,1,0,0,0,0,0,0],
              [0,0,1,0,0,0,0,0],
              [0,0,0,1,0,0,0,0],
              [1,1,1,1,0,0,0,0],
              [0,0,0,0,1,0,0,0],
              [0,0,0,0,1,0,0,0],
              [0,0,0,0,0,1,0,0],
              [0,0,0,0,0,1,0,0],
              [0,0,0,0,0,0,1,0],
              [0,0,0,0,0,0,1,0],
              [0,0,0,0,0,0,0,1],
              [0,0,0,0,0,0,0,1]])
  cons = sp.optimize.LinearConstraint(A, lb = np.zeros(13), ub = np.ones(13))
  bounds = sp.optimize.Bounds(lb = np.zeros(8), ub = np.ones(8))

  #Initial Guess:
  x0 = [0.2, 0.2, 0.2, 0.2, 0.01, 0.01, 0.01, 0.01]

  #Run once with all stations recieving 3 sat measurements
  change_sat_measurements([3,3,3,3,3])
  print("\nAll base stations recieving 3 sat measurements:")
  result = sp.optimize.minimize(fun=MSE, x0=x0, bounds=bounds, constraints=cons)
  print("Optimized Weights Vector: ", np.around(result.x, 4))
  print("\nCorresponding Adjacency Matrix:")
  print(convert_to_adj(np.around(result.x, 4)))
  print("\nResulting MSE: ", round(result.fun, 4))

  #Run once with two edge nodes recieving no sat measurements
  change_sat_measurements([5,0,0,5,5])
  print("\n\nBase stations 2 and 3 recieving no sat measurements, the rest recieving 5:")
  result = sp.optimize.minimize(fun=MSE, x0=x0, bounds=bounds, constraints=cons)
  print("Optimized Weights Vector: ", np.around(result.x, 4))
  print("\nCorresponding Adjacency Matrix:")
  print(convert_to_adj(np.around(result.x, 4)))
  print("\nResulting MSE: ", round(result.fun, 4))

#mse_bfgs()


All base stations recieving 3 sat measurements:
Optimized Weights Vector:  [0.1779 0.1853 0.1779 0.2786 0.0089 0.2488 0.1536 0.0187]

Corresponding Adjacency Matrix:
[[0.1803 0.1779 0.1853 0.1779 0.2786]
 [0.0089 0.9911 0.     0.     0.    ]
 [0.2488 0.     0.7512 0.     0.    ]
 [0.1536 0.     0.     0.8464 0.    ]
 [0.0187 0.     0.     0.     0.9813]]

Resulting MSE:  15.7073


Base stations 2 and 3 recieving no sat measurements, the rest recieving 5:
Optimized Weights Vector:  [0.28  0.18  0.18  0.28  0.009 0.109 0.109 0.109]

Corresponding Adjacency Matrix:
[[0.08  0.28  0.18  0.18  0.28 ]
 [0.009 0.991 0.    0.    0.   ]
 [0.109 0.    0.891 0.    0.   ]
 [0.109 0.    0.    0.891 0.   ]
 [0.109 0.    0.    0.    0.891]]

Resulting MSE:  158709.8434


In [14]:
def change_sat_measurements(msmts):
  global msmts_arr
  msmts_arr = msmts